/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Person;

/**
 *
 * @author sneha
 */
public class MainJFrameParent extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame1
     */
    Person person;
    public MainJFrameParent() {
        initComponents();
        person = new Person();
    }
    public MainJFrameParent(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JPanelParent = new javax.swing.JPanel();
        BtnEnterInfo = new javax.swing.JButton();
        BtnViewInfo = new javax.swing.JButton();
        LblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        JPanelParent.setBackground(new java.awt.Color(150, 200, 220));
        JPanelParent.setForeground(new java.awt.Color(150, 200, 220));
        JPanelParent.setToolTipText("");
        JPanelParent.setAutoscrolls(true);
        JPanelParent.setPreferredSize(new java.awt.Dimension(440, 340));
        JPanelParent.setLayout(new java.awt.GridBagLayout());

        BtnEnterInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnEnterInfo.setText("Enter Infromation");
        BtnEnterInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnterInfoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(85, 119, 201, 0);
        JPanelParent.add(BtnEnterInfo, gridBagConstraints);

        BtnViewInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnViewInfo.setText("View Information");
        BtnViewInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewInfoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(85, 280, 201, 0);
        JPanelParent.add(BtnViewInfo, gridBagConstraints);

        LblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitle.setText("PERSONAL INFROMATION");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 553;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        JPanelParent.add(LblTitle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 274;
        gridBagConstraints.ipady = 190;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(JPanelParent, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEnterInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnterInfoActionPerformed
        // TODO add your handling code here:
        //SubJFrameEnter enterPanel = new SubJFrameEnter(person);
        //SplitPane.setRightComponent(viewPanel);
        this.setVisible(false);
        new SubJFrameEnter(person).setVisible(true);
    }//GEN-LAST:event_BtnEnterInfoActionPerformed

    private void BtnViewInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewInfoActionPerformed
        // TODO add your handling code here
        System.out.println("Inside View Button: " + person.getFirstname());
        this.setVisible(false);
        new SubJFrameView(person).setVisible(true);
    }//GEN-LAST:event_BtnViewInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrameParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrameParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrameParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrameParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrameParent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEnterInfo;
    private javax.swing.JButton BtnViewInfo;
    private javax.swing.JPanel JPanelParent;
    private javax.swing.JLabel LblTitle;
    // End of variables declaration//GEN-END:variables
}
