/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import model.Person;


/**
 *
 * @author sneha
 */
public class SubJFrameView extends javax.swing.JFrame {

    /**
     * Creates new form SubJFrameView
     */
    Person person;
    public SubJFrameView(Person person) {
        initComponents();
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane2 = new javax.swing.JSplitPane();
        JPanelView = new javax.swing.JPanel();
        BtnDemoView = new javax.swing.JButton();
        BtnAddressView = new javax.swing.JButton();
        BtnDLView = new javax.swing.JButton();
        BtnMedRecView = new javax.swing.JButton();
        BtnAccountView = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        BtnGenerate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setAutoscrolls(true);

        JPanelView.setBackground(new java.awt.Color(180, 180, 180));
        JPanelView.setAutoscrolls(true);
        JPanelView.setLayout(new java.awt.GridBagLayout());

        BtnDemoView.setText("Demographic");
        BtnDemoView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDemoViewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 0, 0, 0);
        JPanelView.add(BtnDemoView, gridBagConstraints);

        BtnAddressView.setText("Address");
        BtnAddressView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddressViewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 0, 0, 0);
        JPanelView.add(BtnAddressView, gridBagConstraints);

        BtnDLView.setText("Driver's License");
        BtnDLView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDLViewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 0, 0, 0);
        JPanelView.add(BtnDLView, gridBagConstraints);

        BtnMedRecView.setText("Medical Record");
        BtnMedRecView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMedRecViewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 0, 0, 0);
        JPanelView.add(BtnMedRecView, gridBagConstraints);

        BtnAccountView.setText("Account Info");
        BtnAccountView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAccountViewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        JPanelView.add(BtnAccountView, gridBagConstraints);

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 43, 0, 0);
        JPanelView.add(BtnBack, gridBagConstraints);

        BtnGenerate.setText("Generate Report");
        BtnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 0, 0, 0);
        JPanelView.add(BtnGenerate, gridBagConstraints);

        jSplitPane2.setLeftComponent(JPanelView);

        jPanel2.setBackground(new java.awt.Color(240, 140, 140));
        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(new java.awt.GridBagLayout());
        jSplitPane2.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDemoViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDemoViewActionPerformed
        // TODO add your handling code here:
        System.out.println("Inside demo enter");
        JPanelDemoView viewdemopanel = new JPanelDemoView(person);
        jSplitPane2.setRightComponent(viewdemopanel);
    }//GEN-LAST:event_BtnDemoViewActionPerformed

    private void BtnAddressViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddressViewActionPerformed
        // TODO add your handling code here:
          JPanelAddressView viewaddresspanel = new JPanelAddressView(person);
        jSplitPane2.setRightComponent(viewaddresspanel);
    }//GEN-LAST:event_BtnAddressViewActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrameParent(person).setVisible(true);
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnAccountViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAccountViewActionPerformed
        // TODO add your handling code here:
        JPanelAccountView viewaccountpanel = new JPanelAccountView(person);
        jSplitPane2.setRightComponent(viewaccountpanel);
    }//GEN-LAST:event_BtnAccountViewActionPerformed

    private void BtnDLViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDLViewActionPerformed
        // TODO add your handling code here:
        JPanelDlView viewdlpanel = new JPanelDlView(person);
        jSplitPane2.setRightComponent(viewdlpanel);
    }//GEN-LAST:event_BtnDLViewActionPerformed

    private void BtnMedRecViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMedRecViewActionPerformed
        // TODO add your handling code here:
        JPanelMedRecView viewmedrecpanel = new JPanelMedRecView(person);
        jSplitPane2.setRightComponent(viewmedrecpanel);
    }//GEN-LAST:event_BtnMedRecViewActionPerformed

    private void BtnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerateActionPerformed
        // TODO add your handling code here:
        JPanelGenerateReport viewreportpanel = new JPanelGenerateReport(person);
        jSplitPane2.setRightComponent(viewreportpanel);
    }//GEN-LAST:event_BtnGenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubJFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubJFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubJFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubJFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(new Runnable() {
        //    public void run() {
        //        new SubJFrameView().setVisible(true);
         //   }
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAccountView;
    private javax.swing.JButton BtnAddressView;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnDLView;
    private javax.swing.JButton BtnDemoView;
    private javax.swing.JButton BtnGenerate;
    private javax.swing.JButton BtnMedRecView;
    private javax.swing.JPanel JPanelView;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
}
