/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import model.Person;

/**
 *
 * @author sneha
 */
public class SubJFrameEnter extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Person person;
    public SubJFrameEnter(Person person) {
        initComponents();
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        JPanelEnter = new javax.swing.JPanel();
        BtnDemoEnter = new javax.swing.JButton();
        BtnAddressEnter = new javax.swing.JButton();
        BtnLicense = new javax.swing.JButton();
        BtnMedRec = new javax.swing.JButton();
        BtnAccountEnter = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelEnter.setBackground(new java.awt.Color(180, 180, 180));
        JPanelEnter.setLayout(new java.awt.GridBagLayout());

        BtnDemoEnter.setText("Demographic");
        BtnDemoEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDemoEnterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 0, 0, 10);
        JPanelEnter.add(BtnDemoEnter, gridBagConstraints);

        BtnAddressEnter.setText("Address");
        BtnAddressEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddressEnterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 0, 0, 10);
        JPanelEnter.add(BtnAddressEnter, gridBagConstraints);

        BtnLicense.setText("Driver's License");
        BtnLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLicenseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 0, 0, 10);
        JPanelEnter.add(BtnLicense, gridBagConstraints);

        BtnMedRec.setText("Medical Record");
        BtnMedRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMedRecActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 0, 0, 10);
        JPanelEnter.add(BtnMedRec, gridBagConstraints);

        BtnAccountEnter.setText("Account Info");
        BtnAccountEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAccountEnterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 0, 0, 10);
        JPanelEnter.add(BtnAccountEnter, gridBagConstraints);

        BtnBack.setText("back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 20, 92, 0);
        JPanelEnter.add(BtnBack, gridBagConstraints);

        jSplitPane1.setLeftComponent(JPanelEnter);

        jPanel2.setBackground(new java.awt.Color(207, 140, 200));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new java.awt.GridBagLayout());
        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDemoEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDemoEnterActionPerformed
        // TODO add your handling code here:
        JPanelDemoEnter demoenterpanel = new JPanelDemoEnter(person);
        
        jSplitPane1.setRightComponent(demoenterpanel);
    }//GEN-LAST:event_BtnDemoEnterActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrameParent(person).setVisible(true);
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnAddressEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddressEnterActionPerformed
        // TODO add your handling code here:
        JPanelAddressEnter addressenterpanel = new JPanelAddressEnter(person);
        
        jSplitPane1.setRightComponent(addressenterpanel);
    }//GEN-LAST:event_BtnAddressEnterActionPerformed

    private void BtnAccountEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAccountEnterActionPerformed
        // TODO add your handling code here:
        JPanelAccountEnter accountenterpanel = new JPanelAccountEnter(person);
        
        jSplitPane1.setRightComponent(accountenterpanel);
    }//GEN-LAST:event_BtnAccountEnterActionPerformed

    private void BtnLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLicenseActionPerformed
        // TODO add your handling code here:
        JPanelDlEnter dlenterpanel = new JPanelDlEnter(person);
        
        jSplitPane1.setRightComponent(dlenterpanel);
    }//GEN-LAST:event_BtnLicenseActionPerformed

    private void BtnMedRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMedRecActionPerformed
        // TODO add your handling code here:
        JPanelMedRecEnter medrecenterpanel = new JPanelMedRecEnter(person);
        
        jSplitPane1.setRightComponent(medrecenterpanel);
    }//GEN-LAST:event_BtnMedRecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubJFrameEnter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubJFrameEnter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubJFrameEnter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubJFrameEnter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
       
       // java.awt.EventQueue.invokeLater(new Runnable() {
            
           // public void run() {
           //     new SubJFrameEnter().setVisible(true);
           // }
       // });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAccountEnter;
    private javax.swing.JButton BtnAddressEnter;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnDemoEnter;
    private javax.swing.JButton BtnLicense;
    private javax.swing.JButton BtnMedRec;
    private javax.swing.JPanel JPanelEnter;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
